//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eba5Dal.SapServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="SapServiceReference.ZWSHPA_EBA_ENTGRSYN")]
    public interface ZWSHPA_EBA_ENTGRSYN {
        
        // CODEGEN: Generating message contract since the operation Z_HPA_EBA_ENTEGRASYON is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWSHPA_EBA_ENTGRSYN:Z_HPA_EBA_ENTEGRASYONR" +
            "equest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Eba5Dal.SapServiceReference.Z_HPA_EBA_ENTEGRASYONResponse1 Z_HPA_EBA_ENTEGRASYON(Eba5Dal.SapServiceReference.Z_HPA_EBA_ENTEGRASYONRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_HPA_EBA_ENTEGRASYON : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZSTHPA_EBA_ENTG[] iT_TABLEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSTHPA_EBA_ENTG[] IT_TABLE {
            get {
                return this.iT_TABLEField;
            }
            set {
                this.iT_TABLEField = value;
                this.RaisePropertyChanged("IT_TABLE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSTHPA_EBA_ENTG : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pERNRField;
        
        private int oNERI_IDField;
        
        private string oNERI_ADField;
        
        private string oNERI_TEXTField;
        
        private decimal pARASAL_KAZANCField;
        
        private string gIRIS_TARIHField;
        
        private string kABUL_TARIHField;
        
        private string eK_ALAN1Field;
        
        private string eK_ALAN2Field;
        
        private string eK_ALAN3Field;
        
        private string eK_ALAN4Field;
        
        private string eK_ALAN5Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PERNR {
            get {
                return this.pERNRField;
            }
            set {
                this.pERNRField = value;
                this.RaisePropertyChanged("PERNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int ONERI_ID {
            get {
                return this.oNERI_IDField;
            }
            set {
                this.oNERI_IDField = value;
                this.RaisePropertyChanged("ONERI_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ONERI_AD {
            get {
                return this.oNERI_ADField;
            }
            set {
                this.oNERI_ADField = value;
                this.RaisePropertyChanged("ONERI_AD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ONERI_TEXT {
            get {
                return this.oNERI_TEXTField;
            }
            set {
                this.oNERI_TEXTField = value;
                this.RaisePropertyChanged("ONERI_TEXT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal PARASAL_KAZANC {
            get {
                return this.pARASAL_KAZANCField;
            }
            set {
                this.pARASAL_KAZANCField = value;
                this.RaisePropertyChanged("PARASAL_KAZANC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string GIRIS_TARIH {
            get {
                return this.gIRIS_TARIHField;
            }
            set {
                this.gIRIS_TARIHField = value;
                this.RaisePropertyChanged("GIRIS_TARIH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string KABUL_TARIH {
            get {
                return this.kABUL_TARIHField;
            }
            set {
                this.kABUL_TARIHField = value;
                this.RaisePropertyChanged("KABUL_TARIH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string EK_ALAN1 {
            get {
                return this.eK_ALAN1Field;
            }
            set {
                this.eK_ALAN1Field = value;
                this.RaisePropertyChanged("EK_ALAN1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string EK_ALAN2 {
            get {
                return this.eK_ALAN2Field;
            }
            set {
                this.eK_ALAN2Field = value;
                this.RaisePropertyChanged("EK_ALAN2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string EK_ALAN3 {
            get {
                return this.eK_ALAN3Field;
            }
            set {
                this.eK_ALAN3Field = value;
                this.RaisePropertyChanged("EK_ALAN3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string EK_ALAN4 {
            get {
                return this.eK_ALAN4Field;
            }
            set {
                this.eK_ALAN4Field = value;
                this.RaisePropertyChanged("EK_ALAN4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string EK_ALAN5 {
            get {
                return this.eK_ALAN5Field;
            }
            set {
                this.eK_ALAN5Field = value;
                this.RaisePropertyChanged("EK_ALAN5");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_HPA_EBA_ENTEGRASYONResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eV_TRNSFR_OKField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EV_TRNSFR_OK {
            get {
                return this.eV_TRNSFR_OKField;
            }
            set {
                this.eV_TRNSFR_OKField = value;
                this.RaisePropertyChanged("EV_TRNSFR_OK");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_HPA_EBA_ENTEGRASYONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Eba5Dal.SapServiceReference.Z_HPA_EBA_ENTEGRASYON Z_HPA_EBA_ENTEGRASYON;
        
        public Z_HPA_EBA_ENTEGRASYONRequest() {
        }
        
        public Z_HPA_EBA_ENTEGRASYONRequest(Eba5Dal.SapServiceReference.Z_HPA_EBA_ENTEGRASYON Z_HPA_EBA_ENTEGRASYON) {
            this.Z_HPA_EBA_ENTEGRASYON = Z_HPA_EBA_ENTEGRASYON;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_HPA_EBA_ENTEGRASYONResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Eba5Dal.SapServiceReference.Z_HPA_EBA_ENTEGRASYONResponse Z_HPA_EBA_ENTEGRASYONResponse;
        
        public Z_HPA_EBA_ENTEGRASYONResponse1() {
        }
        
        public Z_HPA_EBA_ENTEGRASYONResponse1(Eba5Dal.SapServiceReference.Z_HPA_EBA_ENTEGRASYONResponse Z_HPA_EBA_ENTEGRASYONResponse) {
            this.Z_HPA_EBA_ENTEGRASYONResponse = Z_HPA_EBA_ENTEGRASYONResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWSHPA_EBA_ENTGRSYNChannel : Eba5Dal.SapServiceReference.ZWSHPA_EBA_ENTGRSYN, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWSHPA_EBA_ENTGRSYNClient : System.ServiceModel.ClientBase<Eba5Dal.SapServiceReference.ZWSHPA_EBA_ENTGRSYN>, Eba5Dal.SapServiceReference.ZWSHPA_EBA_ENTGRSYN {
        
        public ZWSHPA_EBA_ENTGRSYNClient() {
        }
        
        public ZWSHPA_EBA_ENTGRSYNClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWSHPA_EBA_ENTGRSYNClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWSHPA_EBA_ENTGRSYNClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWSHPA_EBA_ENTGRSYNClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eba5Dal.SapServiceReference.Z_HPA_EBA_ENTEGRASYONResponse1 Eba5Dal.SapServiceReference.ZWSHPA_EBA_ENTGRSYN.Z_HPA_EBA_ENTEGRASYON(Eba5Dal.SapServiceReference.Z_HPA_EBA_ENTEGRASYONRequest request) {
            return base.Channel.Z_HPA_EBA_ENTEGRASYON(request);
        }
        
        public Eba5Dal.SapServiceReference.Z_HPA_EBA_ENTEGRASYONResponse Z_HPA_EBA_ENTEGRASYON(Eba5Dal.SapServiceReference.Z_HPA_EBA_ENTEGRASYON Z_HPA_EBA_ENTEGRASYON1) {
            Eba5Dal.SapServiceReference.Z_HPA_EBA_ENTEGRASYONRequest inValue = new Eba5Dal.SapServiceReference.Z_HPA_EBA_ENTEGRASYONRequest();
            inValue.Z_HPA_EBA_ENTEGRASYON = Z_HPA_EBA_ENTEGRASYON1;
            Eba5Dal.SapServiceReference.Z_HPA_EBA_ENTEGRASYONResponse1 retVal = ((Eba5Dal.SapServiceReference.ZWSHPA_EBA_ENTGRSYN)(this)).Z_HPA_EBA_ENTEGRASYON(inValue);
            return retVal.Z_HPA_EBA_ENTEGRASYONResponse;
        }
    }
}
