//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eba5WinServices.SapServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="SapServiceReference.z_hpa_kaza_entegrasyon")]
    public interface z_hpa_kaza_entegrasyon {
        
        // CODEGEN: Generating message contract since the operation ZHpaKazaEntegrasyon is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:z_hpa_kaza_entegrasyon:ZHpaKazaE" +
            "ntegrasyonRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Eba5WinServices.SapServiceReference.ZHpaKazaEntegrasyonResponse1 ZHpaKazaEntegrasyon(Eba5WinServices.SapServiceReference.ZHpaKazaEntegrasyonRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZHpaKazaEntegrasyon : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZsthpaKaza[] itTableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZsthpaKaza[] ItTable {
            get {
                return this.itTableField;
            }
            set {
                this.itTableField = value;
                this.RaisePropertyChanged("ItTable");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZsthpaKaza : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string olayIdField;
        
        private string pernrField;
        
        private string kazaTrhField;
        
        private string kazaTuruField;
        
        private string yaralananUzuvField;
        
        private string olayinOlusSekliField;
        
        private string performansEtkisiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OlayId {
            get {
                return this.olayIdField;
            }
            set {
                this.olayIdField = value;
                this.RaisePropertyChanged("OlayId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Pernr {
            get {
                return this.pernrField;
            }
            set {
                this.pernrField = value;
                this.RaisePropertyChanged("Pernr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string KazaTrh {
            get {
                return this.kazaTrhField;
            }
            set {
                this.kazaTrhField = value;
                this.RaisePropertyChanged("KazaTrh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string KazaTuru {
            get {
                return this.kazaTuruField;
            }
            set {
                this.kazaTuruField = value;
                this.RaisePropertyChanged("KazaTuru");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string YaralananUzuv {
            get {
                return this.yaralananUzuvField;
            }
            set {
                this.yaralananUzuvField = value;
                this.RaisePropertyChanged("YaralananUzuv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string OlayinOlusSekli {
            get {
                return this.olayinOlusSekliField;
            }
            set {
                this.olayinOlusSekliField = value;
                this.RaisePropertyChanged("OlayinOlusSekli");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string PerformansEtkisi {
            get {
                return this.performansEtkisiField;
            }
            set {
                this.performansEtkisiField = value;
                this.RaisePropertyChanged("PerformansEtkisi");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZHpaKazaEntegrasyonResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string evTrnsfrOkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EvTrnsfrOk {
            get {
                return this.evTrnsfrOkField;
            }
            set {
                this.evTrnsfrOkField = value;
                this.RaisePropertyChanged("EvTrnsfrOk");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZHpaKazaEntegrasyonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public Eba5WinServices.SapServiceReference.ZHpaKazaEntegrasyon ZHpaKazaEntegrasyon;
        
        public ZHpaKazaEntegrasyonRequest() {
        }
        
        public ZHpaKazaEntegrasyonRequest(Eba5WinServices.SapServiceReference.ZHpaKazaEntegrasyon ZHpaKazaEntegrasyon) {
            this.ZHpaKazaEntegrasyon = ZHpaKazaEntegrasyon;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZHpaKazaEntegrasyonResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public Eba5WinServices.SapServiceReference.ZHpaKazaEntegrasyonResponse ZHpaKazaEntegrasyonResponse;
        
        public ZHpaKazaEntegrasyonResponse1() {
        }
        
        public ZHpaKazaEntegrasyonResponse1(Eba5WinServices.SapServiceReference.ZHpaKazaEntegrasyonResponse ZHpaKazaEntegrasyonResponse) {
            this.ZHpaKazaEntegrasyonResponse = ZHpaKazaEntegrasyonResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface z_hpa_kaza_entegrasyonChannel : Eba5WinServices.SapServiceReference.z_hpa_kaza_entegrasyon, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class z_hpa_kaza_entegrasyonClient : System.ServiceModel.ClientBase<Eba5WinServices.SapServiceReference.z_hpa_kaza_entegrasyon>, Eba5WinServices.SapServiceReference.z_hpa_kaza_entegrasyon {
        
        public z_hpa_kaza_entegrasyonClient() {
        }
        
        public z_hpa_kaza_entegrasyonClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public z_hpa_kaza_entegrasyonClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public z_hpa_kaza_entegrasyonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public z_hpa_kaza_entegrasyonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eba5WinServices.SapServiceReference.ZHpaKazaEntegrasyonResponse1 Eba5WinServices.SapServiceReference.z_hpa_kaza_entegrasyon.ZHpaKazaEntegrasyon(Eba5WinServices.SapServiceReference.ZHpaKazaEntegrasyonRequest request) {
            return base.Channel.ZHpaKazaEntegrasyon(request);
        }
        
        public Eba5WinServices.SapServiceReference.ZHpaKazaEntegrasyonResponse ZHpaKazaEntegrasyon(Eba5WinServices.SapServiceReference.ZHpaKazaEntegrasyon ZHpaKazaEntegrasyon1) {
            Eba5WinServices.SapServiceReference.ZHpaKazaEntegrasyonRequest inValue = new Eba5WinServices.SapServiceReference.ZHpaKazaEntegrasyonRequest();
            inValue.ZHpaKazaEntegrasyon = ZHpaKazaEntegrasyon1;
            Eba5WinServices.SapServiceReference.ZHpaKazaEntegrasyonResponse1 retVal = ((Eba5WinServices.SapServiceReference.z_hpa_kaza_entegrasyon)(this)).ZHpaKazaEntegrasyon(inValue);
            return retVal.ZHpaKazaEntegrasyonResponse;
        }
    }
}
